### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by christosg88** [abk-openroad/RePlAce#10]
I am attaching the log file created by `script` during `make`.

If you run `cat make_result.log` you can see the terminal output in color.

The error I get is:
`/usr/bin/ld: cannot find -lc++`

[make_result.log](https://github.com/abk-openroad/RePlAce/files/2629207/make_result.log)

**Comment by mgwoo** [comment]
Sorry I have no clues on it.
This is related to OpenSTA's compile issues. 

How about reporting this issue to https://github.com/abk-openroad/OpenSTA ?
