### ISSUE TITLE
Make clean reports a missing target

### ISSUE THREAD

**Issue by ashwin-hari** [abk-openroad/RePlAce#14]
https://github.com/abk-openroad/RePlAce/blob/c77d24f07820ae109c59206a7cb998f8b99f1a94/Makefile#L17-L22

When running make clean, the distclean target is reported as missing:

make[1]: Entering directory `/home/mbt/IDEA/RePlAce/module/sparsehash'
make[1]: *** No rule to make target `distclean'.  Stop.
make[1]: Leaving directory `/home/mbt/IDEA/RePlAce/module/sparsehash'
make: *** [clean] Error 2

A possible mitigation to this issue is to ignore the error.

**Comment by mgwoo** [comment]
Thanks for finding this mistake. Solved in https://github.com/abk-openroad/RePlAce/commit/f387d2363e79afd560e03254dc1d7c926782dee4

Closed
