### ISSUE TITLE
lef.tab.h: No such file or directory.

### ISSUE THREAD

**Issue by ashwin-hari** [abk-openroad/RePlAce#18]
When running make, a "No such file or directory" error is reported for lef.tab.h.
 
https://github.com/abk-openroad/RePlAce/blob/73cb0d39557ef30df3316b3a9f456622857c71c0/module/lef/5.8-p027/lef/lefrSettings.cpp#L34

A possible mitigation to this issue is to ignore the error.

**Comment by mgwoo** [comment]
Solved in commit: https://github.com/abk-openroad/RePlAce/commit/c77d24f07820ae109c59206a7cb998f8b99f1a94
closed
