### ISSUE TITLE
Make: Linker can't find c++ std library

### ISSUE THREAD

**Issue by ashwin-hari** [abk-openroad/RePlAce#19]
Building RePlAce will fail in environments without the C++ std library installation.

https://github.com/abk-openroad/RePlAce/blob/c77d24f07820ae109c59206a7cb998f8b99f1a94/src/Makefile#L83

Perhaps, state this as a prerequisite.

**Comment by mgwoo** [comment]
Solved in commit: https://github.com/abk-openroad/RePlAce/commit/cdc5c5323167918ea838e08d0f7f8efca8b6e132
closed
