### ISSUE TITLE
Density constraint in tier.cpp

### ISSUE THREAD

**Issue by RTimothyEdwards** [abk-openroad/RePlAce#38]
I am finding that I can get errors with RePlAce stopping with the error message "no more tier to assign!".  This happens because I am calculating row sites based on the number of standard cells and the target density.  Slight differences in the calculation between my script and RePlAce, however, mean that RePlAce thinks there are not enough sites for the cells.  But density does not need to be exact.  RePlAce should not care if the density is slightly off, certainly not if the difference is small enough to be round-off error.

I suggest that tier.cpp around line 239:

      if((tier->modu_area + modu_area) / tier->ws_area <=
         target_cell_den - dp_margin_per_tier) {

should instead fail only if tier->modu_area + modu_area) > tier->ws_area (strong constraint).  Otherwise, if the existing expression (above) fails (preferably with a small positive value for dp_margin_per_tier to account for round-off error) (weak constraint), it should flag a warning that the density cannot be met due to lack of sites, but it should not exit.  This is not a fatal condition.

---Tim

**Comment by mgwoo** [comment]
Sorry for my late reply. 
Thanks for reporting. It has been updated.
