### ISSUE TITLE
TD-RePlAce dies when trying to instantiate the OpenSTA object

### ISSUE THREAD

**Issue by tajayi** [abk-openroad/RePlAce#40]
Continuing a debugging thread via email. @Payal can also contribute to this

**Comment by mgwoo** [comment]
This issue is due to "\r\n" on liberty's filename. 

In your Makefile, 

    $$(< $(OBJECTS_DIR)/libFilePaths.txt) 
caused this problem.

I'll escape these strings in my side, just in case.

**Comment by mgwoo** [comment]
Solved. Close.
